
CREATE TABLE Url (Id INTEGER PRIMARY KEY AUTOINCREMENT, Link TEXT);
CREATE TABLE Word (Id INTEGER PRIMARY KEY AUTOINCREMENT, Word TEXT);
CREATE TABLE UrlWordLocation (UrlId INTEGER, WordId INTEGER, Location INTEGER, FOREIGN KEY(UrlId) REFERENCES URL(Id), FOREIGN KEY(WordId) REFERENCES Word(Id));
CREATE TABLE Link (Id INTEGER PRIMARY KEY AUTOINCREMENT, FromId INTEGER, ToId INTEGER, FOREIGN KEY(FromId) REFERENCES URL(Id), FOREIGN KEY(ToId) REFERENCES URL(Id));
CREATE TABLE LinkWords (WordId INTEGER, LinkId INTEGER, FOREIGN KEY(WordId) REFERENCES Word(Id), FOREIGN KEY(LinkId) REFERENCES URL(Id));